// Code generated by gobind. DO NOT EDIT.

// Java class tun2socks.Tun2socks is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java AndrProxy/tun2socks
package tun2socks;

import go.Seq;

public abstract class Tun2socks {
	static {
		Seq.touch(); // for loading the native library
		_init();
	}
	
	private Tun2socks() {} // uninstantiable
	
	// touch is called from other bound packages to initialize this package
	public static void touch() {}
	
	private static native void _init();
	
	
	
	/**
	 * SetLoglevel set tun2socks log level
	possible input: debug/info/warn/error/none
	 */
	public static native void setLoglevel(String logLevel);
	/**
	 * Start sets up lwIP stack, starts a Tun2socks instance
	 */
	public static native long start(Tun2socksStartOptions opt);
	/**
	 * Stop stop it
	 */
	public static native void stop();
}
